---
- name: ansible facts use case example playbook
  hosts: all 
  become: true
  tasks:
    - name: capture the kernal version information
      copy:
        content: "the available kernal version is {{ ansible_kernel }}"
        dest: /tmp/kernel_version.txt