---
- name: variable example
  hosts: web
  vars:
     httpd_port: 80
  tasks:
   - name: just show variable value
     debug:
       msg: "{{ httpd_port }}"
   - name: just show varible value
     vars:
        httpd_port: 90
     debug:
       msg: "tomcat is going to run on {{ httpd_port }}"       